platform :ios, '7.0'

pod 'Swizzlean', '~> 0.1.1'
target 'multiThreadLabTests' do
  pod 'Specta',      '~> 0.2.1'
  pod 'Expecta',     '~> 0.2.4'
  pod 'KIF', '~> 3.0'
  pod 'OCMockito', '~> 1.0'
end

